package output.com.treselle;
class Jeep1 extends VehicleImpl1
{
		Jeep1()
		{
		System.out.println();
		openDoor();
		System.out.println();
		closeDoor();
		System.out.println();
		start();
		System.out.println();
		increaseSpeed();
		System.out.println();
		Door1.turn();
		System.out.println();
		decreaseSpeed();
		System.out.println();
		Door1.horn();
		System.out.println();
		increaseSpeed();
		System.out.println();
		openDoor();
		System.out.println();
		closeDoor();
		System.out.println();
		stop();
		}
}